# Litterae Finis

This repository contains what I believe to be the full source code to my 2013 TMDC-winning demo "Litterae Finis". The only external dependency not included is FMOD, because this project predates SoLoud..

I haven't tried to compile it, so something may be missing.

Pouet page: http://www.pouet.net/prod.php?which=60938
YouTube link: https://www.youtube.com/watch?v=vcK4mF_RHDA
Making of: http://sol.gfxile.net/litterae/
